'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('firmware/web/index.html','utf8');
class Element{constructor(){this.value='';this.children=[];this.style={setProperty(name,value){this[name]=value;}};this.attributes={};}replaceChildren(...v){this.children=v;}append(...v){this.children.push(...v);}setAttribute(name,value){this.attributes[name]=value;}click(){}}
const nodes=new Map();const document={getElementById(id){if(!nodes.has(id))nodes.set(id,new Element());return nodes.get(id);},createElement(){return new Element();},activeElement:null};
let scanResult={scanning:false,networks:[]},scanError=false;
let offline=true,calls=[],holdStatus=null,download=null,hanging=false;const timers=new Map();
const status={name:'CM-Radio',version:'0.1.2',build:'0a02',board:'WROVER',audioReady:true,station:'Test',stationIndex:0,volume:5,autoplay:true,state:'streaming',wifiConnected:true,setupActive:false,storageReady:true,settingsPending:false,ssid:'SECRET-SSID',password:'SECRET-PASSWORD',ip:'PRIVATE-IP',title:'PRIVATE-TITLE',message:'PRIVATE-URL',freeHeap:100000,minFreeHeap:90000,resetReason:1};
const context=vm.createContext({document,AbortController,Date,console,setTimeout(fn,ms){const id=setTimeout(fn,ms===1000?0:ms);timers.set(id,{fn,ms});return id;},clearTimeout(id){timers.delete(id);clearTimeout(id);},setInterval(){},Blob:class{constructor(parts){download=parts.join('');}},URL:{createObjectURL(){return 'blob:test';},revokeObjectURL(){}},async fetch(url,options){calls.push(url);assert.ok(options.signal);if(offline)throw new Error('offline');if(hanging)await new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>{const error=new Error('aborted');error.name='AbortError';reject(error);},{once:true}));if(url.endsWith('/status')&&holdStatus)await holdStatus;if(url.endsWith('/wifi/scan')){if(scanError)throw new Error('Scan fehlgeschlagen');return {ok:true,json:async()=>options.method==='POST'?{accepted:true}:scanResult};}return{ok:true,json:async()=>url.endsWith('/status')?status:url.endsWith('/stations')?{stations:[{name:'Test',url:'https://example.org/stream'}]}:{ssid:'SECRET-SSID',autoplay:true}};}});
const evaluate=s=>vm.runInContext(s,context);
const settled=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 evaluate(html.match(/<script>([\s\S]*?)<\/script>/)[1]);await settled();
 assert.equal(nodes.get('play').disabled,true);
 assert.equal(nodes.get('state').textContent,'Gerät nicht erreichbar');
 offline=false;await evaluate('poll()');
 assert.equal(nodes.get('play').disabled,false);
 assert.equal(nodes.get('stations').children.length,1);
 assert.equal(nodes.get('ssid').value,'SECRET-SSID');
 evaluate("signalStatus({wifiConnected:true,rssi:-50})");assert.equal(nodes.get('signal4').className,'active');assert.equal(nodes.get('signalBars').style['--signal'],'#73dfaa');
 evaluate("signalStatus({wifiConnected:true,rssi:-70})");assert.equal(nodes.get('signal3').className,'');assert.equal(nodes.get('signalBars').style['--signal'],'#f0c76b');
 evaluate("signalStatus({wifiConnected:true,rssi:-85})");assert.equal(nodes.get('signalBars').style['--signal'],'#ef8f83');
 evaluate("signalStatus({wifiConnected:false,setupActive:true})");assert.equal(nodes.get('signalText').textContent,'Einrichtungsmodus');assert.equal(nodes.get('signal1').className,'');
 evaluate("signalStatus({wifiConnected:true,rssi:0})");assert.equal(nodes.get('signal1').className,'');
 nodes.get('navStations').onclick();assert.equal(nodes.get('panelStations').hidden,false);assert.equal(nodes.get('panelListen').hidden,true);assert.equal(nodes.get('navStations').attributes['aria-pressed'],'true');
 nodes.get('openNetwork').onclick();assert.equal(nodes.get('panelNetwork').hidden,false);assert.equal(nodes.get('wifiDetails').open,true);
 nodes.get('navListen').onclick();

 let release;holdStatus=new Promise(resolve=>release=resolve);calls=[];
 const first=evaluate('poll()');await settled();await evaluate('poll()');
 assert.equal(calls.filter(x=>x.endsWith('/status')).length,1);release();await first;holdStatus=null;
 evaluate("editing=true;list=[{name:'Ungespeichert',url:'http://example.org/new'}]");
 offline=true;await evaluate('poll()');offline=false;await evaluate('poll()');
 assert.equal(evaluate('list[0].name'),'Ungespeichert');
 hanging=true;const hung=evaluate('poll()');await settled();
 const timer=[...timers.values()].find(item=>item.ms===6000);assert.ok(timer);timer.fn();await hung;
 assert.equal(evaluate('pollBusy'),false);assert.equal(nodes.get('play').disabled,true);
 hanging=false;await evaluate('poll()');assert.equal(nodes.get('play').disabled,false);
 scanResult={scanning:false,networks:[{ssid:'<WLAN & Test>',rssi:-42,secure:true}]};
 await nodes.get('scanWifi').onclick();
 assert.equal(nodes.get('wifiNetworks').disabled,false);
 assert.equal(nodes.get('wifiNetworks').children[1].textContent,'<WLAN & Test> · -42 dBm · gesichert');
 nodes.get('wifiNetworks').value='<WLAN & Test>';nodes.get('wifiNetworks').onchange();
 assert.equal(nodes.get('ssid').value,'<WLAN & Test>');
 assert.equal(document.getElementById('password').value,'');
 scanResult={scanning:false,networks:[]};await nodes.get('scanWifi').onclick();
 assert.equal(nodes.get('wifiNetworks').disabled,true);assert.match(nodes.get('scanHint').textContent,/Keine Netzwerke/);
 scanError=true;await nodes.get('scanWifi').onclick();
 assert.equal(nodes.get('scanWifi').disabled,false);assert.equal(evaluate('scanBusy'),false);
 scanError=false;
 await nodes.get('diagnostics').onclick();
 const report=JSON.parse(download);assert.equal(report.hardwareAcceptance,'OPEN');assert.equal(report.resetReason,1);assert.equal(report.build,'0a02');
 for(const privateValue of ['SECRET-SSID','SECRET-PASSWORD','PRIVATE-IP','PRIVATE-TITLE','PRIVATE-URL'])assert.ok(!download.includes(privateValue));
 console.log('Web reconnect, request timeout, first-load recovery, polling serialization, unsaved edits and diagnostic privacy: PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
