'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('firmware/web/index.html','utf8');
class Element{constructor(){this.value='';this.children=[];this.style={setProperty(name,value){this[name]=value;}};this.attributes={};}replaceChildren(...v){this.children=v;}append(...v){this.children.push(...v);}removeAttribute(name){delete this.attributes[name];}setAttribute(name,value){this.attributes[name]=value;}click(){}}
const nodes=new Map();const document={getElementById(id){if(!nodes.has(id))nodes.set(id,new Element());return nodes.get(id);},createElement(){return new Element();},activeElement:null};
let holdPreview=null,failPreview=false;
let otaFailure=false,otaUploads=0;
let restoreValid=true;const backupFixture={format:"CM-Radio-Backup",schema:1,settings:{stations:[{name:"Test",url:"https://example.org/stream"}],selected:0,volume:5,volumeLimit:12,softStartSeconds:5,fallbackStation:-1,autoplay:true}};
let scanResult={scanning:false,networks:[]},scanError=false;
let directoryRows=[],directoryFailFirst=false,directoryFailAll=false;
let offline=true,calls=[],requestBodies=[],holdStatus=null,download=null,hanging=false;const timers=new Map();
let stationRows=[{name:'Test',url:'https://example.org/stream'}];
const status={name:'CM-Radio',version:'0.1.3',build:'02',volumeLimit:12,softStartSeconds:5,sleepRemainingSeconds:90,effectiveVolume:2,ramping:true,fallbackStation:-1,fallbackActive:false,board:'WROVER',audioReady:true,station:'Test',stationIndex:0,playingStationIndex:0,volume:5,autoplay:true,state:'streaming',wifiConnected:true,setupActive:false,storageReady:true,settingsPending:false,ssid:'SECRET-SSID',password:'SECRET-PASSWORD',ip:'PRIVATE-IP',title:'PRIVATE-TITLE',message:'PRIVATE-URL',freeHeap:100000,minFreeHeap:90000,resetReason:1};
const context=vm.createContext({XMLHttpRequest:class{constructor(){this.upload={};}open(method,url){assert.equal(method,'POST');assert.equal(url,'/api/v1/update');}setRequestHeader(key,value){assert.equal(key,'X-CM-Update-Token');assert.equal(value,'TEST-TOKEN');}send(data){assert.equal(data.name,'firmware');assert.equal(data.filename,'firmware.bin');otaUploads++;this.upload.onprogress({lengthComputable:true,loaded:100,total:100});this.status=otaFailure?400:200;this.responseText=JSON.stringify(otaFailure?{error:'SHA-256 falsch'}:{message:'Neustart'});this.onload();}},FormData:class{append(name,file,filename){this.name=name;this.file=file;this.filename=filename;}},document,AbortController,Date,console,TextEncoder,URLSearchParams,Intl,Set,setTimeout(fn,ms){const id=setTimeout(fn,ms===1000?0:ms);timers.set(id,{fn,ms});return id;},clearTimeout(id){timers.delete(id);clearTimeout(id);},setInterval(){},Blob:class{constructor(parts){download=parts.join('');}},URL:class extends URL{static createObjectURL(){return 'blob:test';}static revokeObjectURL(){}},async fetch(url,options){calls.push(url);if(options.body)requestBodies.push({url,data:JSON.parse(options.body)});if(!url.endsWith('/update/cancel'))assert.ok(options.signal);if(url.startsWith('https://')){if(directoryFailAll||(directoryFailFirst&&url.includes('de1.')))throw new Error('directory offline');return {ok:true,text:async()=>JSON.stringify(directoryRows)};}if(offline)throw new Error('offline');if(hanging)await new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>{const error=new Error('aborted');error.name='AbortError';reject(error);},{once:true}));if(url.endsWith('/status')&&holdStatus)await holdStatus;if(url.endsWith('/sound/preview')){if(holdPreview)await holdPreview;if(failPreview)throw new Error('Preview offline');return {ok:true,json:async()=>({accepted:true})};}if(url.endsWith('/update/prepare'))return {ok:true,json:async()=>({token:'TEST-TOKEN'})};if(url.endsWith('/update/status'))return {ok:true,json:async()=>({phase:'prepared',audioStopped:true})};if(url.endsWith('/update/cancel'))return {ok:true};if(url.endsWith('/backup'))return {ok:true,json:async()=>backupFixture};if(url.endsWith('/restore/validate'))return {ok:true,json:async()=>({valid:restoreValid,stationCount:1,volume:5,volumeLimit:12})};if(url.endsWith('/restore'))return {ok:true,json:async()=>({accepted:true})};if(url.endsWith('/wifi/scan')){if(scanError)throw new Error('Scan fehlgeschlagen');return {ok:true,json:async()=>options.method==='POST'?{accepted:true}:scanResult};}return{ok:true,json:async()=>url.endsWith('/status')?status:url.endsWith('/stations')?{stations:stationRows}:{ssid:'SECRET-SSID',autoplay:true}};}});
const evaluate=s=>vm.runInContext(s,context);
const settled=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 evaluate(html.match(/<script>([\s\S]*?)<\/script>/)[1]);await settled();
 assert.equal(nodes.get('play').disabled,true);
 assert.equal(nodes.get('state').textContent,'Gerät nicht erreichbar');
 offline=false;await evaluate('poll()');
 assert.equal(nodes.get('play').disabled,false);
 assert.equal(nodes.get('stations').children.length,1);
 assert.equal(nodes.get('ssid').value,'SECRET-SSID');
 assert.equal(nodes.get('quickStations').children.length,1);assert.equal(nodes.get('quickStations').children[0].attributes['aria-pressed'],'true');
 nodes.get('manageQuick').onclick();assert.equal(nodes.get('panelStations').hidden,false);
 await nodes.get('quickStations').children[0].onclick();assert.deepEqual(requestBodies.at(-1).data,{station:0});
 evaluate('online=false;updateQuick()');const beforeQuick=requestBodies.length;await nodes.get('quickStations').children[0].onclick();assert.equal(requestBodies.length,beforeQuick);evaluate('online=true');
 stationRows=[{name:'<A & Test>',url:'https://example.org/a'},{name:'B',url:'https://example.org/b'},{name:'C',url:'https://example.org/c'}];evaluate('loaded=false');await evaluate('poll()');
 assert.equal(nodes.get('quickStations').children[0].children[1].textContent,'<A & Test>');
 evaluate('moveStation(0,1)');assert.equal(evaluate('list[0].name'),'B');assert.equal(evaluate('savedList[0].name'),'<A & Test>');assert.equal(nodes.get('quickStations').children[0].children[1].textContent,'<A & Test>');
 assert.equal(nodes.get('editors').children[0].children[3].children[0].disabled,true);assert.equal(nodes.get('editors').children[2].children[3].children[1].disabled,true);
 evaluate('playbackEditing=true;moveStation(0,1)');assert.equal(evaluate('list[0].name'),'B');evaluate('playbackEditing=false');
 stationRows=JSON.parse(evaluate('JSON.stringify(list)'));await nodes.get('saveStations').onclick();assert.equal(nodes.get('quickStations').children[0].children[1].textContent,'B');assert.equal(requestBodies.at(-1).data.stations[0].name,'B');
 status.fallbackActive=true;status.fallbackStation=2;status.playingStationIndex=1;await evaluate('poll()');assert.equal(nodes.get('quickStations').children[1].attributes['aria-pressed'],'true');assert.equal(nodes.get('quickStations').children[2].attributes['aria-pressed'],'false');assert.equal(nodes.get('quickStations').children[1].children[2].textContent,'Spielt als Ersatzsender');
 status.state='connecting';await evaluate('poll()');assert.ok(nodes.get('quickStations').children.every(button=>button.attributes['aria-pressed']==='false'));
 status.state='streaming';status.fallbackActive=false;status.fallbackStation=-1;status.playingStationIndex=0;stationRows=[{name:'Test',url:'https://example.org/stream'}];evaluate('loaded=false');await evaluate('poll()');
 assert.ok(html.includes('Build 02')&&html.includes('Build 0a01'));assert.ok(html.includes('CHANGELOG_START'));

 evaluate("signalStatus({wifiConnected:true,rssi:-50})");assert.equal(nodes.get('signal4').className,'active');assert.equal(nodes.get('signalBars').style['--signal'],'#73dfaa');
 evaluate("signalStatus({wifiConnected:true,rssi:-70})");assert.equal(nodes.get('signal3').className,'');assert.equal(nodes.get('signalBars').style['--signal'],'#f0c76b');
 evaluate("signalStatus({wifiConnected:true,rssi:-85})");assert.equal(nodes.get('signalBars').style['--signal'],'#ef8f83');
 evaluate("signalStatus({wifiConnected:false,setupActive:true})");assert.equal(nodes.get('signalText').textContent,'Einrichtungsmodus');assert.equal(nodes.get('signal1').className,'');
 evaluate("signalStatus({wifiConnected:true,rssi:0})");assert.equal(nodes.get('signal1').className,'');
 nodes.get('navStations').onclick();assert.equal(nodes.get('panelStations').hidden,false);assert.equal(nodes.get('panelListen').hidden,true);assert.equal(nodes.get('navStations').attributes['aria-pressed'],'true');
 nodes.get('openNetwork').onclick();assert.equal(nodes.get('panelNetwork').hidden,false);assert.equal(nodes.get('wifiDetails').open,true);
 nodes.get('navListen').onclick();

 let release;holdStatus=new Promise(resolve=>release=resolve);calls=[];
 const first=evaluate('poll()');await settled();await evaluate('poll()');
 assert.equal(calls.filter(x=>x.endsWith('/status')).length,1);release();await first;holdStatus=null;
 evaluate("editing=true;list=[{name:'Ungespeichert',url:'http://example.org/new'}]");
 offline=true;await evaluate('poll()');offline=false;await evaluate('poll()');
 assert.equal(evaluate('list[0].name'),'Ungespeichert');
 hanging=true;const hung=evaluate('poll()');await settled();
 const timer=[...timers.values()].find(item=>item.ms===6000);assert.ok(timer);timer.fn();await hung;
 assert.equal(evaluate('pollBusy'),false);assert.equal(nodes.get('play').disabled,true);
 hanging=false;await evaluate('poll()');assert.equal(nodes.get('play').disabled,false);
 scanResult={scanning:false,networks:[{ssid:'<WLAN & Test>',rssi:-42,secure:true}]};
 await nodes.get('scanWifi').onclick();
 assert.equal(nodes.get('wifiNetworks').disabled,false);
 assert.equal(nodes.get('wifiNetworks').children[1].textContent,'<WLAN & Test> · -42 dBm · gesichert');
 nodes.get('wifiNetworks').value='<WLAN & Test>';nodes.get('wifiNetworks').onchange();
 assert.equal(nodes.get('ssid').value,'<WLAN & Test>');
 assert.equal(document.getElementById('password').value,'');
 scanResult={scanning:false,networks:[]};await nodes.get('scanWifi').onclick();
 assert.equal(nodes.get('wifiNetworks').disabled,true);assert.match(nodes.get('scanHint').textContent,/Keine Netzwerke/);
 scanError=true;await nodes.get('scanWifi').onclick();
 assert.equal(nodes.get('scanWifi').disabled,false);assert.equal(evaluate('scanBusy'),false);
 scanError=false;
 nodes.get('searchScope').value='local';document.getElementById('searchCountry').value='DE';document.getElementById('searchQuery').value='Berlin & Umgebung';
 directoryRows=[{name:'<Radio & Test>',favicon:'https://example.org/radio.png',url_resolved:'https://example.org/live',codec:'MP3',country:'Deutschland',state:'Berlin',bitrate:128},{name:'Duplikat',url:'https://example.org/live',codec:'MP3'},{name:'HLS',url:'https://example.org/a.m3u8',codec:'AAC',hls:1},{name:'Script',url:'javascript:alert(1)',codec:'MP3'}];
 directoryFailFirst=true;calls=[];
 await nodes.get('searchForm').onsubmit({preventDefault(){}});
 assert.equal(nodes.get('searchResults').children.length,1);assert.equal(nodes.get('searchResults').children[0].children[0].textContent,'<Radio & Test>');
 assert.ok(calls.some(url=>url.includes('countrycode=DE')&&url.includes('state=Berlin')));assert.ok(calls.some(url=>url.includes('nl1.')));
 const addButton=nodes.get('searchResults').children[0].children[2];addButton.onclick();assert.equal(evaluate('list.at(-1).logo'),'https://example.org/radio.png');assert.equal(evaluate('list.length'),2);assert.equal(evaluate('editing'),true);
 addButton.onclick();assert.equal(evaluate('list.length'),2);
 directoryFailAll=true;await nodes.get('searchForm').onsubmit({preventDefault(){}});assert.equal(nodes.get('searchButton').disabled,false);assert.equal(evaluate('list.length'),2);assert.match(nodes.get('searchHint').textContent,/Gespeicherte Sender/);
 directoryFailAll=false;directoryFailFirst=false;directoryRows=[];await nodes.get('searchForm').onsubmit({preventDefault(){}});assert.match(nodes.get('searchHint').textContent,/Keine passenden/);
 evaluate("list=Array.from({length:10},(_,i)=>({name:'Test '+i,url:'http://example.org/'+i}))");evaluate("addSearchStation({name:'Neu',url:'http://example.org/new'},document.getElementById('searchButton'))");assert.equal(evaluate('list.length'),10);
 nodes.get('searchScope').value='international';nodes.get('searchScope').onchange();assert.equal(nodes.get('searchCountry').disabled,true);calls=[];await nodes.get('searchForm').onsubmit({preventDefault(){}});assert.ok(calls.filter(url=>url.includes('/stations/search')).every(url=>!url.includes('countrycode=')));
 directoryRows=[{name:'DE'},{name:'AT'},null,{name:'invalid'}];document.getElementById('searchCountry').value='DE';await nodes.get('loadCountries').onclick();assert.equal(nodes.get('searchCountry').children.length,2);assert.equal(nodes.get('searchCountry').value,'DE');
 assert.equal(evaluate("supportedStation({name:'A',url:'https://user:pass@example.org/live',codec:'AAC'})"),null);
 assert.equal(evaluate("supportedStation({name:'A',url:'https://example.org/live',codec:'FLAC'})"),null);
 assert.ok(evaluate("new TextEncoder().encode(supportedStation({name:'Ä'.repeat(100),url:'https://example.org/live',codec:'AAC'}).name).length")<=63);
 nodes.get('searchScope').value='local';nodes.get('searchQuery').value='';calls=[];await nodes.get('searchForm').onsubmit({preventDefault(){}});assert.equal(calls.length,0);
 evaluate('online=false');evaluate("addSearchStation({name:'Neu',url:'http://example.org/another'},document.getElementById('searchButton'))");assert.equal(evaluate('list.length'),10);evaluate('online=true');
 assert.equal(nodes.get('volume').max,'12');assert.equal(nodes.get('sleepRemaining').textContent,'1:30 verbleibend');evaluate('lastStatus.sleepRemainingSeconds=0;connection(true)');assert.equal(nodes.get('sleepCancel').disabled,true);evaluate('lastStatus.sleepRemainingSeconds=90;connection(true)');assert.equal(nodes.get('sleepCancel').disabled,false);
 document.getElementById('volumeLimit').value='8';nodes.get('volumeLimit').oninput();await evaluate('refresh()');assert.equal(nodes.get('volumeLimit').value,'8');
 evaluate('editing=false');document.getElementById('softStartSeconds').value='3';await nodes.get('playbackForm').onsubmit({preventDefault(){}});assert.deepEqual(requestBodies.at(-1).data,{volumeLimit:8,softStartSeconds:3,fallbackStation:-1});
 await nodes.get('sleep15').onclick();assert.deepEqual(requestBodies.at(-1).data,{minutes:15});await nodes.get('sleepCancel').onclick();assert.deepEqual(requestBodies.at(-1).data,{minutes:0});
 const requestCount=requestBodies.length;document.getElementById('sleepMinutes').value='181';await nodes.get('sleepForm').onsubmit({preventDefault(){}});assert.equal(requestBodies.length,requestCount);
 await nodes.get('backupDownload').onclick();assert.equal(JSON.parse(download).format,'CM-Radio-Backup');assert.ok(!download.includes('SECRET'));
 const backupFile={size:500,text:async()=>JSON.stringify(backupFixture)};nodes.get('restoreFile').files=[backupFile];nodes.get('restoreFile').onchange();await nodes.get('restoreCheck').onclick();assert.equal(nodes.get('restoreApply').disabled,false);
 evaluate('editing=true');const beforeRestore=requestBodies.length;await nodes.get('restoreApply').onclick();assert.equal(requestBodies.length,beforeRestore);evaluate('editing=false');
 await nodes.get('restoreApply').onclick();assert.ok(requestBodies.some(r=>r.url.endsWith('/restore')&&r.data.format==='CM-Radio-Backup'));assert.equal(evaluate('restoreCandidate'),null);assert.equal(nodes.get('restoreApply').disabled,true);
 restoreValid=false;await nodes.get('restoreCheck').onclick();assert.equal(nodes.get('restoreApply').disabled,true);restoreValid=true;
 nodes.get('restoreFile').files=[{size:20000,text:async()=>{throw new Error('Must not read oversized file');}}];const beforeOversize=requestBodies.length;await nodes.get('restoreCheck').onclick();assert.equal(requestBodies.length,beforeOversize);
 let releaseFile;nodes.get('restoreFile').files=[{size:500,text:()=>new Promise(resolve=>releaseFile=resolve)}];const checking=nodes.get('restoreCheck').onclick();await settled();nodes.get('restoreFile').files=[backupFile];nodes.get('restoreFile').onchange();releaseFile(JSON.stringify(backupFixture));await checking;assert.equal(evaluate('restoreCandidate'),null);
 document.getElementById('bass').value='2';nodes.get('bass').oninput();document.getElementById('bass').value='3';nodes.get('bass').oninput();await evaluate('flushPreview()');assert.deepEqual(requestBodies.at(-1).data,{bass:3,treble:0,balance:0,loudness:false});assert.ok(requestBodies.at(-1).url.endsWith('/sound/preview'));assert.equal(evaluate('soundEditing'),true);
 let releasePreview;holdPreview=new Promise(resolve=>releasePreview=resolve);document.getElementById('bass').value='4';nodes.get('bass').oninput();const previewRequest=evaluate('flushPreview()');await settled();document.getElementById('bass').value='5';nodes.get('bass').oninput();const saveDuringPreview=nodes.get('soundForm').onsubmit({preventDefault(){}});await settled();assert.equal(nodes.get('soundSave').disabled,true);releasePreview();await previewRequest;await saveDuringPreview;holdPreview=null;assert.ok(requestBodies.at(-1).url.endsWith('/config'));assert.deepEqual(requestBodies.at(-1).data,{bass:5,treble:0,balance:0,loudness:false});assert.equal(evaluate('previewPromise'),null);
 document.getElementById('balance').value='16';nodes.get('balance').oninput();await evaluate('flushPreview()');await nodes.get('soundRevert').onclick();assert.ok(requestBodies.at(-1).url.endsWith('/sound/reset'));assert.equal(nodes.get('balance').value,'0');assert.equal(evaluate('soundEditing'),false);
 failPreview=true;document.getElementById('bass').value='1';nodes.get('bass').oninput();await evaluate('flushPreview()');assert.equal(evaluate('previewPromise'),null);assert.match(nodes.get('soundHint').textContent,/fehlgeschlagen/);failPreview=false;await nodes.get('soundRevert').onclick();
 document.getElementById('bass').value='4';nodes.get('bass').oninput();document.getElementById('treble').value='-3';nodes.get('treble').oninput();document.getElementById('balance').value='-16';nodes.get('balance').oninput();await evaluate('poll()');assert.equal(nodes.get('bass').value,'4');assert.equal(nodes.get('bassValue').textContent,'+4 dB');assert.equal(nodes.get('balanceValue').textContent,'Links 16 / 16');await nodes.get('soundForm').onsubmit({preventDefault(){}});assert.deepEqual(requestBodies.at(-1).data,{bass:4,treble:-3,balance:-16,loudness:false});assert.equal(evaluate('soundEditing'),false);
 nodes.get('soundReset').onclick();assert.equal(nodes.get('bass').value,'0');assert.equal(evaluate('soundEditing'),true);await nodes.get('soundForm').onsubmit({preventDefault(){}});assert.deepEqual(requestBodies.at(-1).data,{bass:0,treble:0,balance:0,loudness:false});const beforeBadSound=requestBodies.length;document.getElementById('balance').value='17';await nodes.get('soundForm').onsubmit({preventDefault(){}});assert.equal(requestBodies.length,beforeBadSound);document.getElementById('balance').value='0';
 document.getElementById('loudness').checked=true;nodes.get('loudness').onchange();await evaluate('flushPreview()');assert.equal(requestBodies.at(-1).data.loudness,true);await nodes.get('soundForm').onsubmit({preventDefault(){}});assert.equal(requestBodies.at(-1).data.loudness,true);
 assert.equal(evaluate("trackInfo('Artist - Song - Live').artist"),'Artist');assert.equal(evaluate("trackInfo('Artist - Song - Live').title"),'Song - Live');assert.equal(evaluate("trackInfo('Only title').artist"),'');assert.equal(evaluate("validLogo('javascript:alert(1)')"),'');assert.equal(evaluate("validLogo('http://example.org/logo.png')"),'');assert.equal(evaluate("validLogo('https://user:pass@example.org/logo.png')"),'');
 evaluate("renderTrack({title:'<Artist> - <Song>',message:'Stream',state:'streaming'})");assert.equal(nodes.get('title').textContent,'<Song>');assert.equal(nodes.get('artist').textContent,'<Artist>');evaluate("renderTrack({title:'',state:'streaming'})");assert.equal(nodes.get('artist').hidden,true);assert.match(nodes.get('title').textContent,/Kein Titel/);
 evaluate("renderLogo({station:'A',stationLogo:'https://example.org/a.png'})");const firstLogo=nodes.get('coverLogo').children[0];firstLogo.onload();assert.equal(nodes.get('coverDisc').hidden,true);evaluate("renderLogo({station:'B',stationLogo:'https://example.org/b.png'})");firstLogo.onerror();assert.equal(nodes.get('coverLogo').children.length,1);const secondLogo=nodes.get('coverLogo').children[0];secondLogo.onerror();assert.equal(nodes.get('coverLogo').hidden,true);assert.equal(nodes.get('coverDisc').hidden,false);evaluate("renderLogo({station:'B',stationLogo:'https://example.org/b.png'})");assert.equal(nodes.get('coverLogo').children[0],secondLogo);evaluate("renderLogo({station:'No logo',stationLogo:''})");assert.equal(nodes.get('coverDisc').hidden,false);
 const updateManifest={name:'CM-Radio',chip:'esp32',flashSize:8388608,version:'0.1.3',build:'02',update:{target:'CM-Radio-WROVER-N8R8',file:'firmware.bin',size:2048,sha256:'a'.repeat(64)}};
 const manifestFile={size:800,text:async()=>JSON.stringify(updateManifest)},firmwareFile={name:'firmware.bin',size:2048};nodes.get('updateManifest').files=[manifestFile];nodes.get('updateFirmware').files=[firmwareFile];await nodes.get('updateCheck').onclick();assert.ok(evaluate('updateCandidate'));assert.equal(nodes.get('updateInstall').disabled,true);
 document.getElementById('updateConfirm').checked=true;nodes.get('updateConfirm').onchange();assert.equal(nodes.get('updateInstall').disabled,false);
 evaluate('soundEditing=true');await nodes.get('updateInstall').onclick();assert.equal(otaUploads,0);evaluate('soundEditing=false');evaluate('editing=true');await nodes.get('updateInstall').onclick();assert.equal(otaUploads,0);evaluate('editing=false');await nodes.get('updateInstall').onclick();assert.equal(otaUploads,1);assert.equal(evaluate('updateBusy'),false);assert.equal(evaluate('updateCandidate'),null);assert.match(nodes.get('updateHint').textContent,/aktiviert/);
 await nodes.get('updateCheck').onclick();document.getElementById('updateConfirm').checked=true;otaFailure=true;await nodes.get('updateInstall').onclick();assert.equal(otaUploads,2);assert.equal(evaluate('updateBusy'),false);assert.match(nodes.get('updateHint').textContent,/SHA-256 falsch/);assert.ok(calls.some(url=>url.endsWith('/update/cancel')));otaFailure=false;
 nodes.get('updateFirmware').files=[{name:'full.bin',size:2048}];nodes.get('updateFirmware').onchange();await nodes.get('updateCheck').onclick();assert.equal(evaluate('updateCandidate'),null);assert.equal(nodes.get('updateInstall').disabled,true);
 status.updating=true;await evaluate('poll()');assert.equal(nodes.get('play').disabled,true);assert.equal(nodes.get('quickStations').children[0].disabled,true);status.updating=false;await evaluate('poll()');assert.equal(nodes.get('play').disabled,false);
 await nodes.get('diagnostics').onclick();
 const report=JSON.parse(download);assert.equal(report.hardwareAcceptance,'OPEN');assert.equal(report.resetReason,1);assert.equal(report.build,'02');
 for(const privateValue of ['SECRET-SSID','SECRET-PASSWORD','PRIVATE-IP','PRIVATE-TITLE','PRIVATE-URL'])assert.ok(!download.includes(privateValue));
 console.log('Web reconnect, request timeout, first-load recovery, polling serialization, unsaved edits and diagnostic privacy: PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
