[platformio]
default_envs = loud_wrover

[env:loud_wrover]
platform = espressif32@6.9.0
board = esp-wrover-kit
framework = arduino
platform_packages =
    platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_upload.flash_size = 8MB
board_upload.maximum_size = 3145728
board_build.partitions = partitions.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=0
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12
    bblanchon/ArduinoJson@6.21.5
